// Build build/icon.ico from the square logo PNG (build/icon-256.png,
// generated by the packaging script). png-to-ico embeds multiple sizes.
const fs = require('fs');
const path = require('path');
const pngToIco = require('png-to-ico');

const src = path.join(__dirname, '..', 'build', 'icon-256.png');
const out = path.join(__dirname, '..', 'build', 'icon.ico');

pngToIco(src)
  .then((buf) => {
    fs.writeFileSync(out, buf);
    console.log('icon.ico written:', buf.length, 'bytes');
  })
  .catch((err) => {
    console.error('icon generation failed:', err);
    process.exit(1);
  });
